server:
  port: 8081

spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      port: 27017

logging:
  level:
    root: INFO
  file:
    name: "logFile.log"
    path: /

management:
  endpoints:
    web:
      exposure:
        # Включить метрики, healthchecks и logfile.
        include: metrics,health,logfile
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  health:
    defaults:
      enabled: true
