server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
