version: "3.9"
services:
  book-catalog-10:
    build: .
    container_name: book-catalog-10
    ports:
      - "8081:8081"
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:4.0.10
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"





