server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      port: 27017

hystrix:
  command:
    generateReport:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
      requestLog:
        enabled: true