version: "3.9"
services:
  book-catalog-17:
    build: .
    container_name: book-catalog-10
    environment:
      - DB_HOST=mongo-db
      - DB_PORT=27017
      - DB_NAME=mongo-db
    networks:
      - gateway
    ports:
      - "8081:8081"
#    links:
#      - mongo-db
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:4.0.10
    container_name: mongo-db
    restart: always
    hostname: mongo-db
    ports:
      - '27017:27017'
    networks:
      - gateway
networks:
  gateway:





