version: "3.9"
services:
  book-catalog-10:
    build: .
    container_name: book-catalog-10
    ports:
      - "8081:8081"
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:4.0.10
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
  book-catalog-db:
    # Название image, который нужно поднять
    image: postgres:14.4
    # Имя контейнера, то же что и --name
    container_name: book-catalog-db
    environment:
      POSTGRES_DB: book-catalog-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: parol
    ports:
      - "5433:5432"





